trigger: # This line to run the pipline when push any code to the main branch
  branches: 
    include:
      - main

pr: # This line to run the pipeline when pull request is merged to main branch
  branches:
    include:
      - main

variables:
- group: SYNC_TOKENS

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none

  - script: |
      git clone --bare https://$(AZURE_DEVOPS_PAT)@dev.azure.com/xxx/repo.git repo.git
      cd repo.git
      git remote add github https://$(GITHUB_TOKEN)@github.com/MohammadDarAbed/WebPalMAzad.git
      git push github --all --force
      git push github --tags --force
    displayName: Mirror entire repo from Azure DevOps to GitHub