trigger: # This line to run the pipline when push any code to the main branch
  branches: 
    include:
      - main

pr: # This line to run the pipeline when pull request is merged to main branch
  branches:
    include:
      - main

variables:
- group: SYNC_TOKENS

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none

  - script: |
      echo "AZURE_DEVOPS_PAT length: ${#AZURE_DEVOPS_PAT}"

      git clone --mirror https://user:$(AZURE_DEVOPS_PAT)@dev.azure.com/PalMazad/PalMazad/_git/WebPalMazad repo.git
      cd repo.git

      git push --mirror https://$(GITHUB_TOKEN)@github.com/MohammadDarAbed/WebPalMazad.git
    displayName: 'Mirror entire repo from Azure DevOps to GitHub'
